// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDigAIHvqUmnuVg8bdybw76EFJBt1aa6O8',
    appId: '1:991914845428:web:1778dbaa412ab66b722aa1',
    messagingSenderId: '991914845428',
    projectId: 'cargpt-sg',
    authDomain: 'cargpt-sg.firebaseapp.com',
    storageBucket: 'cargpt-sg.firebasestorage.app',
    measurementId: 'G-34BE2D2DBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhllH4_opu1UHBHfA4x4voDJ-FqujibGw',
    appId: '1:991914845428:android:87ed41f43bcfbf98722aa1',
    messagingSenderId: '991914845428',
    projectId: 'cargpt-sg',
    storageBucket: 'cargpt-sg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlMkct-hYo7itqnQaKEGdFHJ4sK0jMBsQ',
    appId: '1:991914845428:ios:98c23c979260627c722aa1',
    messagingSenderId: '991914845428',
    projectId: 'cargpt-sg',
    storageBucket: 'cargpt-sg.firebasestorage.app',
    iosBundleId: 'com.example.testPk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlMkct-hYo7itqnQaKEGdFHJ4sK0jMBsQ',
    appId: '1:991914845428:ios:98c23c979260627c722aa1',
    messagingSenderId: '991914845428',
    projectId: 'cargpt-sg',
    storageBucket: 'cargpt-sg.firebasestorage.app',
    iosBundleId: 'com.example.testPk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDigAIHvqUmnuVg8bdybw76EFJBt1aa6O8',
    appId: '1:991914845428:web:d3a2a3936e9d7334722aa1',
    messagingSenderId: '991914845428',
    projectId: 'cargpt-sg',
    authDomain: 'cargpt-sg.firebaseapp.com',
    storageBucket: 'cargpt-sg.firebasestorage.app',
    measurementId: 'G-61ZQ70C3JF',
  );
}
