// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSqaeUmjL-n8mxKlWOkmZ9ngvnFmWsBk',
    appId: '1:748686934785:web:f5c8cf52c7a5e7b2dd5100',
    messagingSenderId: '748686934785',
    projectId: 'chatbot-1833c',
    authDomain: 'chatbot-1833c.firebaseapp.com',
    databaseURL: 'https://chatbot-1833c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-1833c.firebasestorage.app',
    measurementId: 'G-5KGC8Z5HLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCgZHNJyTozFcrI14ISEOoa8x1pWX_B4E',
    appId: '1:748686934785:android:b892fc8343761ee2dd5100',
    messagingSenderId: '748686934785',
    projectId: 'chatbot-1833c',
    databaseURL: 'https://chatbot-1833c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-1833c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC56wuZxt1IUm14p2nV7xm5_zRNuRD3WnQ',
    appId: '1:748686934785:ios:43b1a51e00c6c359dd5100',
    messagingSenderId: '748686934785',
    projectId: 'chatbot-1833c',
    databaseURL: 'https://chatbot-1833c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-1833c.firebasestorage.app',
    iosBundleId: 'com.example.testPk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC56wuZxt1IUm14p2nV7xm5_zRNuRD3WnQ',
    appId: '1:748686934785:ios:43b1a51e00c6c359dd5100',
    messagingSenderId: '748686934785',
    projectId: 'chatbot-1833c',
    databaseURL: 'https://chatbot-1833c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-1833c.firebasestorage.app',
    iosBundleId: 'com.example.testPk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoSqaeUmjL-n8mxKlWOkmZ9ngvnFmWsBk',
    appId: '1:748686934785:web:d4c81cee74a1228ddd5100',
    messagingSenderId: '748686934785',
    projectId: 'chatbot-1833c',
    authDomain: 'chatbot-1833c.firebaseapp.com',
    databaseURL: 'https://chatbot-1833c-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-1833c.firebasestorage.app',
    measurementId: 'G-V5XZH6LT38',
  );

}